[project]

name = "back_projection_diffusion"
description = "Solving Inverse Scattering Problem with Diffusion Models"
readme = "README.md"
requires-python = ">=3.11"
license = {file = "LICENSE"}
authors = [
  {name = "Borong Zhang", email="borongzhang@yahoo.com"},
]
classifiers = [  # List of https://pypi.org/classifiers/
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: Apache Software License",
    "Intended Audience :: Science/Research",
]
keywords = [
  "diffusion", "machine learning", "jax", "inverse scattering problem"
]

# pip dependencies of the project
# Installed locally with `pip install -e .`
dependencies = [
  "absl-py",
  "chex",
  "clu",
  "etils",
  "flax",
  "h5py",
  "grain-nightly",
  "gin-config",
  "jax",
  "matplotlib",
  "numpy",
  "optax",
  "orbax-checkpoint",
  "tensorflow",
  "tqdm",
  "xarray",
  "xarray_tensorstore",
  "pyyaml",
  "jax[cuda12_pip] @ https://storage.googleapis.com/jax-releases/jax_cuda_releases.html",
  "pysteps",
  "ott-jax==0.4.7",
]

# `version` is automatically set by flit to use `swirl_dynamics.__version__`

packages = ["back_projection_diffusion"]
dynamic = ["version"]

[project.urls]
homepage = "https://borongzhang.com/"
repository = "https://github.com/borongzhang/back_projection_diffusion"
# Other: `documentation`, `changelog`

[project.optional-dependencies]
# Development deps (unittest, linting, formating,...)
# Installed through `pip install -e .[dev]`
dev = [
    "pytest",
    "pytest-xdist",
    "pylint>=2.6.0",
    "pyink",
]

# Conda-specific dependencies
conda = [
    "jupyter",
    "matplotlib",
    "natsort",
]

[tool.pyink]
# Formatting configuration to follow Google style-guide
line-length = 80
preview = true
pyink-indentation = 2
pyink-use-majority-quotes = true

[build-system]
# Build system specify which backend is used to build/install the project (flit,
# poetry, setuptools,...). All backends are supported by `pip install`
requires = ["flit_core >=3.8,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.sdist]
# Flit specific options (files to exclude from the PyPI package).
# If using another build backend (setuptools, poetry), you can remove this
# section.
exclude = [
  # Do not release tests files on PyPI
  "**/*_test.py",
]
